set_property SRC_FILE_INFO {cfile:C:/Users/passp/fpga/SPI_FAST_BULK_SLAVE_EXAMPLE/SPI_FAST_BULK_SLAVE_EXAMPLE.srcs/constrs_1/new/data_test.xdc rfile:../../../SPI_FAST_BULK_SLAVE_EXAMPLE.srcs/constrs_1/new/data_test.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    M16         [get_ports {multi_spi_miso}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    M15         [get_ports {multi_spi_clk}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    L15         [get_ports {multi_spi_cs}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4         [get_ports    clk]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16        [get_ports    led]
